services:
  - type: web
    name: reparacion-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reparacion-db
          property: connectionString
databases:
  - name: reparacion-db
